export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST"
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS"
export const ADD_MEMBER_FAIL = "ADD_MEMBER_FAIL"

export const GET_MEMBERS_ERROR = "GET_MEMBERS_ERROR"
export const GET_MEMBERS_RECEIVE = "GET_MEMBERS_RECEIVE"
export const GET_MEMBERS_REQUEST = "GET_MEMBERS_REQUEST"

export const GET_MEMBERS_TYPES_RECEIVE = "GET_MEMBERS_TYPES_RECEIVE"
export const GET_MEMBERS_TYPE_RECEIVE = "GET_MEMBERS_TYPE_RECEIVE"

export const GET_MEMBER_RECEIVE = "GET_MEMBER_RECEIVE"
export const GET_MEMBERS_IN_GYM_RECEIVE = "GET_MEMBERS_IN_GYM_RECEIVE"